### ISSUE TITLE
Changing language changes cards

### ISSUE THREAD

**Issue by begarco** [BBS007/bbs007.github.io#5]
It would be nice if clicking on the little pretty flags only translate the cards and do not change them.

**Comment by BBS007** [comment]
This is not how it is supposed to be. You choose the language of the game and then you play it.

**Comment by begarco** [comment]
So you should lock this buttons maybe.

**Comment by BBS007** [comment]
The GUI is not definitive.
Maybe a first screen will ask for language and nickname, then create a game room
