### ISSUE TITLE
White space at the bottom

### ISSUE THREAD

**Issue by begarco** [BBS007/bbs007.github.io#6]
The design is very nice but it would be better if there were something at the bottom : rescale the table or something else.

**Comment by BBS007** [comment]
Would you like the main board to fill the entire screen?

**Comment by begarco** [comment]
I'm not sure, I found the idea to be at the edge of the table interessant but something misses at the bottom.

**Comment by BBS007** [comment]
The table is not full screen. Layout may change again.
Closing this for now
